name: chikabooks_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ▼▼▼ 모든 Firebase 패키지를 충돌 없던 이전 버전으로 되돌립니다 ▼▼▼
  firebase_core: ^2.16.2
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.6.5
  firebase_storage: ^11.6.5
  # ▲▲▲ 모든 Firebase 패키지를 충돌 없던 이전 버전으로 되돌립니다 ▲▲▲

  google_sign_in: ^6.3.0
  shimmer: ^3.0.0
  firebase_messaging: ^14.7.10
  badges: ^3.1.2    

  epubx: ^4.0.0
  archive: ^3.4.9
  image: ^3.3.0

  epub_view: ^3.2.0
  path_provider: ^2.1.2
  http: ^1.2.1
  file_selector: ^1.0.3

  in_app_purchase: ^3.2.1
  in_app_purchase_android: ^0.4.0+1
  
  # PDF 뷰어
  pdfx: ^2.6.0

  cupertino_icons: ^1.0.8
  fl_chart: ^0.66.0
  pedometer: ^4.1.1
  provider: ^6.1.2
  intl: ^0.18.1
  flutter_naver_map: ^1.2.3
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/characters/
    - assets/characters/unicorn1/
    - assets/characters/unicorn1/idle1/
    - assets/characters/unicorn1/idle2/
    - assets/characters/unicorn1/eating/
    - assets/characters/unicorn1/happy/
    - assets/characters/unicorn1/jump/
    - assets/characters/unicorn1/die/
    - assets/characters/unicorn1/flying/
    - assets/characters/unicorn1/horn/
    - assets/characters/unicorn1/no/
    - assets/characters/unicorn1/rest/
    - assets/characters/unicorn1/run/
    - assets/characters/unicorn1/sleep/
    - assets/characters/unicorn1/walk/
    - assets/dreamy background/
    - assets/home/

  # 폰트 파일이 실제 assets/fonts 폴더에 있을 경우 주석을 해제하여 사용합니다.
  # fonts:
  #   - family: NotoSansKR
  #     fonts:
  #       - asset: assets/fonts/NotoSansKR-Thin.otf
  #         weight: 100
  #       - asset: assets/fonts/NotoSansKR-Light.otf
  #         weight: 300
  #       - asset: assets/fonts/NotoSansKR-Regular.otf
  #         weight: 400
  #       - asset: assets/fonts/NotoSansKR-Medium.otf
  #         weight: 500
  #       - asset: assets/fonts/NotoSansKR-Bold.otf
  #         weight: 700
  #       - asset: assets/fonts/NotoSansKR-Black.otf
  #         weight: 900